language: nix
nix: 2.2.2

notifications:
  email: false

branches:
  only:
    - master
    - travis

git:
  quiet: true
  depth: 1

cache:
  directories:
    # Cabal
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.cabal/bin

before_install:
  - export LC_ALL=C
  - export PATH=$HOME/.cabal/bin:$HOME/.nix-profile/bin:$PATH

install:
  - ./cabal --version
  - ./cabal new-update
  - ./cabal new-install --disable-optimization --enable-deterministic --dependencies-only
  - ./cabal new-build   --disable-optimization --enable-deterministic --enable-tests all

script:
  - ./cabal new-run exe:liquidator-swagger

before_cache:
  # Cabal
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/00-index*
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/01-index*
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/*.json
  - rm -rf $HOME/.cabal/packages/hackage.haskell.org/hackage-security-lock
