verbatim:
  cabal-version: 2.4

name: liquidator-redux
version: 0.1.0.0

license: 'AGPL-3.0-or-later'
author: Joachim Fasting
maintainer: joachifm@fastmail.fm

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints
  -fhide-source-paths
  -Wno-unused-imports
  -ddump-to-file
  -ddump-simpl
  -Wall-missed-specialisations
  -fspecialise-aggressively
  -fexpose-all-unfoldings

dependencies:
  - async
  - base
  - bytestring
  - containers
  - directory
  - lens
  - mtl
  - text
  - time

  - aeson
  - aeson-casing
  - cookie
  - fast-logger
  - http-api-data
  - http-types
  - jose
  - lucid
  - optparse-applicative
  - servant
  - servant-auth-server
  - servant-lucid
  - servant-server
  - wai
  - wai-extra
  - warp
  - warp-tls

  - digestive-functors
  - ekg
  - scotty
  - servant-elm
  - servant-swagger
  - swagger2
  - uuid

library:
  source-dirs: src
  exposed-modules:
    - Liquidator.Types
    - Liquidator.Web.Api
    - Liquidator.Web.Server
    - Liquidator.Web.Types

executables:
  liquidator-server:
    main: server.hs
    source-dirs:
      - app
      - src

    ghc-options: -threaded -rtsopts

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src

    cpp-options: -DTEST

    ghc-options: -O0 -threaded "-with-rtsopts=-N"

    dependencies:
      - QuickCheck
      - hspec
      - quickcheck-instances
      - servant-quickcheck

    build-tools:
      - hspec-discover
