verbatim:
  cabal-version: 2.4

name: liquidator-redux
version: 0.1.0.0

license: 'AGPL-3.0-or-later'
author: Joachim Fasting
maintainer: joachifm@fastmail.fm

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints
  -fhide-source-paths

dependencies:
  - base
  - bytestring
  - containers
  - lens
  - mtl
  - text
  - time

  - aeson
  - http-api-data
  - jose
  - lucid
  - servant
  - servant-auth
  - servant-auth-server
  - servant-lucid
  - servant-server
  - wai
  - wai-extra
  - warp
  - warp-tls

  - aeson-casing
  - ekg
  - fast-logger
  - optparse-applicative
  - servant-swagger
  - swagger2
  - uuid

library:
  source-dirs: src
  exposed-modules:
    - Liquidator
    - Money

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src

    cpp-options: -DTEST

    dependencies:
      - hspec
      - QuickCheck

    build-tools:
      - hspec-discover
