verbatim:
  cabal-version: 2.4

name: liquidator-redux
version: 0.1.0.0

license: 'AGPL-3.0-or-later'
author: Joachim Fasting
maintainer: joachifm@fastmail.fm

default-extensions:
  StrictData

ghc-options:
  -Wno-unused-top-binds
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints
  -ddump-deriv
  -ddump-simpl
  -ddump-splices
  -ddump-to-file
  -fhide-source-paths

dependencies:
  # Haskell Platform
  - async
  - base
  - bytestring
  - containers
  - deepseq
  - mtl
  - text
  - time

  - aeson
  - aeson-casing
  - auto-update
  - cookie
  - http-api-data
  - lens-family
  - lens-family-th
  - lucid
  - servant
  - servant-lucid
  - servant-server
  - swagger2
  - servant-swagger
  - uuid
  - wai
  - warp

library:
  source-dirs: src
  exposed-modules:
    - Liquidator.Api
    - Liquidator.Types
    - Liquidator.Web.Server

executables:
  liquidator-web-front-server:
    main: web-front-server.hs
    source-dirs:
      - app
      - src

    ghc-options:
      -threaded
      -rtsopts
      -fspecialise-aggressively
      -fexpose-all-unfoldings

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src

    cpp-options: -DTEST
    ghc-options: -O0 -threaded "-with-rtsopts=-N"

    dependencies:
      - QuickCheck
      - generic-arbitrary
      - hspec
      - quickcheck-instances

    build-tools:
      - hspec-discover
