verbatim:
  cabal-version: 2.4

name: liquidator-redux
version: 0.1.0.0

license: 'AGPL-3.0-or-later'
author: Joachim Fasting
maintainer: joachifm@fastmail.fm

default-extensions:
  StrictData

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints
  -fhide-source-paths
  -fspecialise-aggressively
  -fexpose-all-unfoldings

dependencies:
  - async ^>=2.2.1
  - base ^>=4.12.0
  - bytestring ^>=0.10.8
  - containers ^>=0.6.0
  - microlens-platform ^>=0.3.11
  - mtl ^>=2.2.2
  - text ^>=1.2.3
  - time ^>=1.8.0

  - aeson ^>=1.4.2
  - aeson-casing ^>=0.1.1.0
  - cookie ^>=0.4.4
  - http-api-data ^>=0.3.10
  - http-types ^>=0.12.3
  - lucid ^>=2.9.11
  - optparse-applicative ^>=0.14.3.0
  - servant ^>=0.14.1
  - servant-lucid ^>=0.9
  - servant-server ^>=0.14.1
  - uuid ^>=1.3.13
  - wai ^>=3.2.2
  - wai-extra ^>=3.0.25
  - warp ^>=3.2.26

  # - digestive-functors
  # - ekg
  # - fast-logger
  # - jose
  # - scotty
  # - servant-auth-server
  # - servant-elm
  # - servant-swagger
  # - swagger2
  # - warp-tls

library:
  source-dirs: src
  exposed-modules:
    - Liquidator.Types
    - Liquidator.Web.Api
    - Liquidator.Web.Server
    - Liquidator.Web.Types

executables:
  liquidator-server:
    main: server.hs
    source-dirs:
      - app
      - src

    ghc-options: -threaded -rtsopts

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src

    cpp-options: -DTEST

    ghc-options: -O0 -threaded "-with-rtsopts=-N"

    dependencies:
      - QuickCheck
      - hspec
      - quickcheck-instances
      - servant-quickcheck

    build-tools:
      - hspec-discover
