verbatim:
  cabal-version: 2.4

name: liquidator-redux
version: 0.1.0.0

license: 'AGPL-3.0-or-later'
author: Joachim Fasting
maintainer: joachifm@fastmail.fm

default-extensions:
  StrictData

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints
  -fhide-source-paths
  -fspecialise-aggressively
  -fexpose-all-unfoldings
  -ddump-to-file
  -ddump-simpl
  -ddump-splices

dependencies:
  - async ^>=2.2.1
  - base ^>=4.12.0
  - bytestring ^>=0.10.8
  - containers ^>=0.6.0
  - deepseq ^>=1.4.4.0
  - lens-family
  - lens-family-th
  - mtl ^>=2.2.2
  - text ^>=1.2.3
  - time ^>=1.8.0

  - aeson ^>=1.4.2
  - aeson-casing ^>=0.1.1.0
  - auto-update ^>=0.1.4
  - cookie ^>=0.4.4
  - digestive-functors ^>=0.8.4
  - digestive-functors-lucid
  - http-api-data ^>=0.3.10
  - http-types ^>=0.12.3
  - lucid ^>=2.9.11
  - optparse-applicative ^>=0.14.3.0
  - servant ^>=0.14.1
  - servant-lucid ^>=0.9
  - servant-server ^>=0.14.1
  - servant-swagger ^>=1.1.6
  - swagger2 ^>=2.3.1.1
  - uuid ^>=1.3.13
  - wai ^>=3.2.2
  - wai-extra ^>=3.0.25
  - warp ^>=3.2.26

  - ekg
  - fast-logger
  - lens-family
  - lens-family-th

  # - jose
  # - servant-auth-server
  # - servant-elm
  # - warp-tls

library:
  source-dirs: src
  exposed-modules:
    - Liquidator.Api
    - Liquidator.Types
    - Liquidator.Web.Server

executables:
  liquidator-web-front-server:
    main: web-front-server.hs
    source-dirs:
      - app
      - src

    ghc-options: -threaded -rtsopts

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test/spec
      - src

    cpp-options: -DTEST
    ghc-options: -O0 -threaded "-with-rtsopts=-N"

    dependencies:
      - QuickCheck
      - generic-arbitrary
      - hspec
      - quickcheck-instances
      - servant-quickcheck

    build-tools:
      - hspec-discover

  doctest:
    main: doctest-driver.hs
    source-dirs:
      - test/doctest

    cpp-options: -DTEST
    ghc-options: -O0 -threaded "-with-rtsopts=-N"

    dependencies:
      - doctest

    build-tools:
      - doctest-discover
